
[corruption]
	#Spread speed of corrupted grass blocks, 1 = Default, 0 = Disabled
	#Range: 0.0 ~ 5.0
	"Corruption Spread Speed" = 0.0
	#Should the corrupted tree be able to grow through and destroy blocks? Default = true
	"Corrupted Tree Grow Trough" = false
	#Should corrupted sapling require bone meal to grow at all? Default = false
	"Corrupted Tree Bone Meal" = false
	#Should boblings spawn projectiles when hit and replace blocks when planting? Default = true
	"Corrupted Bobling Griefing" = false
	#Should sludges shoot projectiles when blocks get destroyed? Default = true
	"Corrupted Sludge Griefing" = false

[rebrewing]
	#Change items for rebrewing recipe, JEI needs rejoin
	"Rebrewing Length" = "minecraft:redstone"
	"Rebrewing Amplifier" = "minecraft:glowstone_dust"
	"Rebrewing Splash" = "minecraft:gunpowder"
	"Rebrewing Lingering" = "minecraft:dragon_breath"

